---
name: CI

on:
    workflow_dispatch:
    push:
        branches:
        - main
        paths:
        - "src/**"
        - "pom.xml"
    pull_request:
        branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the project
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Run unit tests
      run: mvn test -B -ff
